spring:
  application:
    name: ware-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.130:8848
server:
  port: 8090
db:
  name: gulimall_wms
model:
  name: ware
mybatis-plus:
  type-aliases-package: com.sia.ware.domain
  configuration:
    map-underscore-to-camel-case: true