spring:
  application:
    name: product-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.130:8848
server:
  port: 8081
db:
  name: gulimall_pms
model:
  name: product
mybatis-plus:
  type-aliases-package: com.sia.product.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl