spring:
  application:
    name: order-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.130:8848
server:
  port: 8087
db:
  name: gulimall_oms
model:
  name: order
  level: info
mybatis-plus:
  type-aliases-package: com.sia.order.domain
  configuration:
    map-underscore-to-camel-case: true