spring:
  application:
    name: member-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.130:8848
db:
  name: gulimall_ums
server:
  port: 8080
mybatis-plus:
  type-aliases-package: com.sia.member.domain
  configuration:
    map-underscore-to-camel-case: true