spring:
  application:
    name: coupon-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.130:8848
server:
  port: 8086
db:
  name: gulimall_sms
model:
  name: coupon
mybatis-plus:
  type-aliases-package: com.sia.coupon.domain
  configuration:
    map-underscore-to-camel-case: true